import * as THREE from 'three';
const renderer = new THREE.WebGLRenderer();
renderer.setSize( window.innerWidth, window.innerHeight );
document.body.appendChild( renderer.domElement );
const SCENE = new THREE.Scene();
const CAMERA = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 0.1, 1000 );
const axesHelper = new THREE.AxesHelper( 5 );
SCENE.add( axesHelper );
CAMERA.position.z = 5;
renderer.render( SCENE, CAMERA );